In [5]:
import numpy as np

9 mark important concepts
--> Max
--> Min
--> Sum

In [6]:
a = np.random.randint(1,100,size=(3,4))
print(a)

print(np.max(a))
print(np.max(a,axis=0)) # max in colwise
print(np.max(a,axis=1)) # max in rowwise

print(np.min(a))
print(np.min(a,axis=0)) # min in colwise
print(np.min(a,axis=1)) # min in rowwise

print(np.sum(a))
print(np.sum(a,axis=1)) # row wise sum
print(np.sum(a,axis=0)) # col wise sum

print(np.sort(a,axis=0)) # col wise sort
print(np.sort(a,axis=1)) # row wise sort

[[83 17 95 54]
 [65 83 96 26]
 [ 9 67 36 52]]
96
[83 83 96 54]
[95 96 67]
9
[ 9 17 36 26]
[17 26  9]
683
[249 270 164]
[157 167 227 132]
[[ 9 17 36 26]
 [65 67 95 52]
 [83 83 96 54]]
[[17 54 83 95]
 [26 65 83 96]
 [ 9 36 52 67]]


In [7]:
import numpy as np
a=np.array([[15,19,14],[20,22,25],[10,8,9],[7,10,12]])
print(a)
b=list(a)
b.sort(key=lambda x:x[-1])
print(np.array(b))
np.argsort(a[:,-1])
a[np.argsort(a[:,-1])]

[[15 19 14]
 [20 22 25]
 [10  8  9]
 [ 7 10 12]]
[[10  8  9]
 [ 7 10 12]
 [15 19 14]
 [20 22 25]]


array([[10,  8,  9],
       [ 7, 10, 12],
       [15, 19, 14],
       [20, 22, 25]])

In [10]:
a=np.array([[1,5,7],[2,5,1],[1,8,1]])
print(a)
print(np.where(a==1))
print(np.where(a==1 , 100,0))
b=np.array([[30,20,40],[50,60,70],[10,30,50]])
print(b)
print(np.where(b>50,1,np.where(b>30,2,3)))

[[1 5 7]
 [2 5 1]
 [1 8 1]]
(array([0, 1, 2, 2]), array([0, 2, 0, 2]))
[[100   0   0]
 [  0   0 100]
 [100   0 100]]
[[30 20 40]
 [50 60 70]
 [10 30 50]]
[[3 3 2]
 [2 1 1]
 [3 3 2]]
