In [3]:
# to use numpy in vs code "pip install numpy" in console
import numpy as np

In [15]:
a=np.array((1,2,3,4))
print(a)
print(type(a))
print()
t=np.array([[1,2],[3,4],[5,6]])
print(t)
print()
p=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(p)


[1 2 3 4]
<class 'numpy.ndarray'>

[[1 2]
 [3 4]
 [5 6]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
a=np.arange(1,11) #Range
print(a)
b=np.arange(11,0,-1) # Stepsize
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[11 10  9  8  7  6  5  4  3  2  1]


In [26]:
# program = 2D and mcq = 3D array
x=np.arange(1,13).reshape(3,4) # a matrix of 3 rows and 4 columns
print(x) # 3x4 must equals to 12 (the range) otherwise Error
print()
x=np.arange(1,13).reshape(3,2,2) #3D array
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [29]:
a=np.ones((3,3)) # 3x3 matrix of all element=1
b=np.zeros((3,4)) # 3x4 matrix of all element=0
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
c=np.identity(3) # 3x3 identity matrix
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
c=np.random.random((3,3))
print(c)
a=np.random.randint(100,1000,size=(3,3)) # random digits with range 100 to 1000
print(a)

[[0.55657288 0.74394076 0.79490881]
 [0.77744965 0.87719888 0.31564498]
 [0.92814803 0.07424668 0.08782893]]
[[793 441 154]
 [815 319 661]
 [118 898 662]]


In [57]:
a=np.round(c*100) # above c matrix multiplied by 100
print(a)

[[56. 74. 79.]
 [78. 88. 32.]
 [93.  7.  9.]]


In [7]:
a=np.arange(1,13)
b=np.arange(1,13).reshape(3,4)
c=np.arange(1,13).reshape(2,3,2)

print(a.ndim) #dimension
print(a.size)
print(a.shape)  # this will 100% come in mcq for dimension 1D
print(b.shape) 
print(a.itemsize)
print(a.dtype)

1
12
(12,)
(3, 4)
8
int64


In [23]:
# slicing in 1D
a=np.arange(1,13)
print(a[0])
print(a[4])
print(a[8])
print(a[4:9])
print(a[ : :-1])
print(a[[1,7,9]]) # something new
print(a[a%2==0]) # another new thing

b=np.arange(1,11)
print(b[(b%3==0) & (b%6==0)])

1
5
9
[5 6 7 8 9]
[12 11 10  9  8  7  6  5  4  3  2  1]
[ 2  8 10]
[ 2  4  6  8 10 12]
[6]


In [55]:
# slicing in 2D
a=np.arange(1,13).reshape(3,4)
print(a)
print(a[1][2])
print(a[1,2]) # above OR this (two methods)
print(a[-1,-3])
print(a[:,0]) # 1st column
print(a[::-1,::-1]) # reverse matrix
print(a[::2,[0,3]])
print(a[::2,::3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
7
10
[1 5 9]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 1  4]
 [ 9 12]]
[[ 1  4]
 [ 9 12]]


In [69]:
# slicing in 3D
a=np.arange(1,13).reshape(2,2,3)
print(a)
print(a[1,0,1])
print(a[::-1,::-1,::-1])
print(a[::,::2,::2])
print(a[::,0,::2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
8
[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]
[[[1 3]]

 [[7 9]]]
[[1 3]
 [7 9]]


In [78]:
# scaler operation

a=np.arange(1,13).reshape(3,4)
print(a)
print(a+5)
print(a-5)
print(a*5)
print(a/5)
print(a%5)
print(a**5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[-4 -3 -2 -1]
 [ 0  1  2  3]
 [ 4  5  6  7]]
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]]
[[1 2 3 4]
 [0 1 2 3]
 [4 0 1 2]]
[[     1     32    243   1024]
 [  3125   7776  16807  32768]
 [ 59049 100000 161051 248832]]


In [80]:
b=np.arange(13,25).reshape(3,4)
print(b)
print(a+b)
print(a-b)
print(a*b) # its wrong so we will use different method
# print(np.dot(a,b))
print(a/b)
print(a//b)
print(a**b)
print(a%b)


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[ 13  28  45  64]
 [ 85 108 133 160]
 [189 220 253 288]]
[[0.07692308 0.14285714 0.2        0.25      ]
 [0.29411765 0.33333333 0.36842105 0.4       ]
 [0.42857143 0.45454545 0.47826087 0.5       ]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[                   1                16384             14348907
            4294967296]
 [        762939453125      101559956668416    11398895185373143
   1152921504606846976]
 [-1261475310744950487  1864712049423024128  6839173302027254275
  -5124814900970913792]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
